CREATE DATABASE TESTING;
CREATE SCHEMA IF NOT EXISTS PI_FLOW_LOAD_TEST;

CREATE TABLE IF NOT EXISTS PI_FLOW_LOAD_TEST.LT_INVOCATION_AUDIT (
    audit_id NUMBER AUTOINCREMENT,
    dag_task_name STRING,
    invoked_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    note STRING
);

CREATE OR REPLACE PROCEDURE PI_FLOW_LOAD_TEST.SP_LT_SLEEP_2S(DAG_TASK_NAME STRING)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    CALL SYSTEM$WAIT(2);
    INSERT INTO PI_FLOW_LOAD_TEST.LT_INVOCATION_AUDIT(dag_task_name, note)
        VALUES (:DAG_TASK_NAME, 'sp_lt_sleep_2s invoked');
    RETURN 'OK:' || :DAG_TASK_NAME;
END;

CREATE OR REPLACE PROCEDURE PI_FLOW_LOAD_TEST.SP_LT_SLEEP_3S(DAG_TASK_NAME STRING)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
    CALL SYSTEM$WAIT(3);
    INSERT INTO PI_FLOW_LOAD_TEST.LT_INVOCATION_AUDIT(dag_task_name, note)
        VALUES (:DAG_TASK_NAME, 'sp_lt_sleep_3s invoked');
    RETURN 'OK:' || :DAG_TASK_NAME;
END;



CREATE OR REPLACE DBT PROJECT TESTING.PI_FLOW_LOAD_TEST.DBT_LT_PROJECT
  FROM 'snow://workspace/USER$.PUBLIC.DEFAULT$/versions/live/DBT_LT_PROJECT'
  COMMENT = 'Lightweight dbt heartbeat project for orchestrator testing';



CREATE OR REPLACE NOTEBOOK PROJECT TESTING.PI_FLOW_LOAD_TEST.NB_LT_PROJECT
  FROM 'snow://workspace/USER$.PUBLIC.DEFAULT$/versions/live'
  COMMENT = 'Lightweight sleep and audit insert notebook project';



CREATE OR REPLACE DBT PROJECT PI_FLOW_LOAD_TEST.DBT_LT_PROJECT
    FROM '@PI_FLOW_LOAD_TEST.LT_STAGE/dbt_lt_project.zip';

-- Optional quick smoke validation.
CALL PI_FLOW_LOAD_TEST.SP_LT_SLEEP_2S('smoke_call_1');
CALL PI_FLOW_LOAD_TEST.SP_LT_SLEEP_3S('smoke_call_2');
